version: '3.8'

services:
  db:
    image: postgres:15.7-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    container_name: db
    networks:
      - nginx-network

  nginx:
    image: nginx:1.27.0-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-network
    depends_on:
      - backend
    ports:
      - 80:80

  backend:
    build: ./example-backend
    # ports:
    #   - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - nginx-network

  frontend:
    build: ./example-frontend
    # ports:
    #   - 5000:5000
    networks:
      - nginx-network

  redis:
    image: redis:7.0.15-alpine
    ports:
      - 6379:6379
    networks:
      - nginx-network

networks:
  nginx-network:
    name: nginx-network
